version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install
      - run:
          name: Run Tests
          command: pip run test
